use anyhow::Result;
use rusqlite::{params, Connection};
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::db::SegmentRow;

pub fn export(
    conn: &Connection,
    data_dir: &Path,
    recording_id: i64,
    formats: &[String],
) -> Result<Vec<String>> {
    let segments = crate::db::get_segments(conn, recording_id)?;
    let meta = load_meta(conn, recording_id)?;
    let out_dir = data_dir.join("exports").join(recording_id.to_string());
    std::fs::create_dir_all(&out_dir)?;

    let mut produced = Vec::new();
    for fmt in formats {
        let path = match fmt.as_str() {
            "vtt" => write_vtt(&out_dir, &segments, &meta)?,
            "json" => write_json(&out_dir, &segments, &meta)?,
            "md" => write_md(&out_dir, &segments, &meta)?,
            other => anyhow::bail!("unknown export format: {other}"),
        };
        let now = chrono::Utc::now().to_rfc3339();
        conn.execute(
            "INSERT INTO exports(recording_id, format, file_path, exported_at, speakers_confirmed)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![recording_id, fmt, path.to_string_lossy(), now, 1],
        )?;
        produced.push(path.to_string_lossy().to_string());
    }
    Ok(produced)
}

struct Meta {
    recording_id: i64,
    source: String,
    app_name: Option<String>,
    imported_at: String,
    duration: Option<f64>,
}

fn load_meta(conn: &Connection, recording_id: i64) -> Result<Meta> {
    Ok(conn.query_row(
        "SELECT id, source, app_name, imported_at, duration_seconds FROM recordings WHERE id = ?1",
        params![recording_id],
        |r| {
            Ok(Meta {
                recording_id: r.get(0)?,
                source: r.get(1)?,
                app_name: r.get(2)?,
                imported_at: r.get(3)?,
                duration: r.get(4)?,
            })
        },
    )?)
}

fn write_vtt(out_dir: &Path, segments: &[SegmentRow], meta: &Meta) -> Result<PathBuf> {
    let path = out_dir.join("transcript.vtt");
    let mut f = File::create(&path)?;

    let speakers: Vec<String> = {
        let mut s: Vec<String> = segments
            .iter()
            .filter_map(|s| s.speaker_name.clone())
            .collect();
        s.sort();
        s.dedup();
        s
    };

    writeln!(f, "WEBVTT\n")?;
    writeln!(f, "NOTE")?;
    writeln!(
        f,
        "Recorded: {}",
        meta.imported_at.replace('T', " ").split('.').next().unwrap_or(&meta.imported_at)
    )?;
    writeln!(
        f,
        "Source: {}{}",
        meta.source,
        meta.app_name
            .as_deref()
            .map(|a| format!("_{a}"))
            .unwrap_or_default()
    )?;
    writeln!(
        f,
        "Duration: {}",
        meta.duration.map(fmt_duration).unwrap_or_else(|| "?".into())
    )?;
    writeln!(f, "Speakers: {}", speakers.join(", "))?;
    writeln!(f, "Generated by: notetaker v0.1\n")?;

    let merged = merge_consecutive(segments);
    for cue in merged {
        writeln!(f, "{} --> {}", fmt_vtt_time(cue.start), fmt_vtt_time(cue.end))?;
        let speaker = cue.speaker.as_deref().unwrap_or("Unknown");
        writeln!(f, "<v {speaker}>{}\n", cue.text)?;
    }
    Ok(path)
}

fn write_json(out_dir: &Path, segments: &[SegmentRow], meta: &Meta) -> Result<PathBuf> {
    let path = out_dir.join("transcript.json");
    let payload = serde_json::json!({
        "recording_id": meta.recording_id,
        "source": meta.source,
        "app_name": meta.app_name,
        "imported_at": meta.imported_at,
        "duration_seconds": meta.duration,
        "segments": segments,
    });
    std::fs::write(&path, serde_json::to_vec_pretty(&payload)?)?;
    Ok(path)
}

fn write_md(out_dir: &Path, segments: &[SegmentRow], meta: &Meta) -> Result<PathBuf> {
    let path = out_dir.join("transcript.md");
    let mut f = File::create(&path)?;
    writeln!(f, "# Transcript — recording #{}\n", meta.recording_id)?;
    writeln!(f, "- Source: {}", meta.source)?;
    if let Some(app) = &meta.app_name {
        writeln!(f, "- App: {app}")?;
    }
    writeln!(f, "- Recorded: {}", meta.imported_at)?;
    if let Some(d) = meta.duration {
        writeln!(f, "- Duration: {}", fmt_duration(d))?;
    }
    writeln!(f)?;
    let merged = merge_consecutive(segments);
    for cue in merged {
        let speaker = cue.speaker.as_deref().unwrap_or("Unknown");
        writeln!(f, "**{speaker}** ({}): {}", fmt_md_time(cue.start), cue.text)?;
    }
    Ok(path)
}

struct Cue {
    start: f64,
    end: f64,
    speaker: Option<String>,
    text: String,
}

fn merge_consecutive(segments: &[SegmentRow]) -> Vec<Cue> {
    let mut out: Vec<Cue> = Vec::new();
    for s in segments {
        let text = s.text.trim();
        if text.is_empty() {
            continue;
        }
        let same_speaker = out
            .last()
            .map(|c| c.speaker == s.speaker_name)
            .unwrap_or(false);
        let small_gap = out
            .last()
            .map(|c| s.start_seconds - c.end <= 1.0)
            .unwrap_or(false);
        let last_short = out.last().map(|c| c.end - c.start < 12.0).unwrap_or(false);

        if same_speaker && small_gap && last_short {
            let last = out.last_mut().unwrap();
            last.end = s.end_seconds;
            last.text.push(' ');
            last.text.push_str(text);
        } else {
            out.push(Cue {
                start: s.start_seconds,
                end: s.end_seconds,
                speaker: s.speaker_name.clone(),
                text: text.to_string(),
            });
        }
    }
    // Split monologues longer than ~15s on sentence boundaries.
    let mut split_out = Vec::new();
    for cue in out {
        if cue.end - cue.start <= 15.0 {
            split_out.push(cue);
            continue;
        }
        let sentences = split_sentences(&cue.text);
        if sentences.len() <= 1 {
            split_out.push(cue);
            continue;
        }
        let total_chars: usize = sentences.iter().map(|s| s.len()).sum();
        let dur = cue.end - cue.start;
        let mut t = cue.start;
        for s in sentences {
            let frac = s.len() as f64 / total_chars.max(1) as f64;
            let end = (t + dur * frac).min(cue.end);
            split_out.push(Cue {
                start: t,
                end,
                speaker: cue.speaker.clone(),
                text: s,
            });
            t = end;
        }
    }
    split_out
}

fn split_sentences(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut buf = String::new();
    for c in text.chars() {
        buf.push(c);
        if matches!(c, '.' | '?' | '!') {
            let s = buf.trim();
            if !s.is_empty() {
                out.push(s.to_string());
            }
            buf.clear();
        }
    }
    let s = buf.trim();
    if !s.is_empty() {
        out.push(s.to_string());
    }
    out
}

fn fmt_vtt_time(t: f64) -> String {
    let h = (t / 3600.0).floor() as u32;
    let m = ((t % 3600.0) / 60.0).floor() as u32;
    let s = t % 60.0;
    let whole = s.floor() as u32;
    let ms = ((s - whole as f64) * 1000.0).round() as u32;
    format!("{h:02}:{m:02}:{whole:02}.{ms:03}")
}

fn fmt_md_time(t: f64) -> String {
    let m = (t / 60.0).floor() as u32;
    let s = (t % 60.0).floor() as u32;
    format!("{m}:{s:02}")
}

fn fmt_duration(t: f64) -> String {
    let h = (t / 3600.0).floor() as u32;
    let m = ((t % 3600.0) / 60.0).floor() as u32;
    let s = (t % 60.0).floor() as u32;
    format!("{h:02}:{m:02}:{s:02}")
}
